### ISSUE TITLE
그리드 ui 구축 여부

### ISSUE THREAD

**Issue by monaq** [dbfilm/gallery#2]
예시
- non-grid: http://hideakihamada.com
  - pros
    - 작품에 포커스를 맞출 수 있다.
  - cons
    - 개발요소가 딱히없다.
- grid: m.daum.net
  - pros
    - 개발할 거리가 많아진다. (정진우의 푸로젝투에 도움이 댄당.)
    - 한 view 안에 많은 작품을 노출할 수 있다.
  - cons: 
    - 개발할 거리가 많아진다.
    - 방문자가 그리드만 보고 세부 이미지에 접근하지 않을수 있다.

의견 부탁드립니다.

**Comment by jayjnu** [comment]
개인적으로는 그리드를 넣는것이 좋을것 같네요.

- 그리드 관련 알고리즘을 이번기회에 정리할 수 있음
- 오히려 그리드를 통해 더 많은 컨텐츠를 한페이지에 표시할 수 있다는 점

**Comment by monaq** [comment]
그리드 구축으로 정리하겠습니다. 감사합니다.
